### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by anonimal** [EinMByte/salti#3]
From [today's meeting](https://github.com/monero-project/kovri/issues/405):

```
meeting-bot | [anonimal] Ok, so maybe what we should do now then is write a definite roadmap/readme that will give others a better understanding of wth we are talking about.
meeting-bot | [anonimal] s/definite/definitive/
+EinMByte | anonimal: That's probably a good idea.
meeting-bot | [anonimal] EinMByte: I think we can easily do that for now. Then, once we are more certain about our webext strategy, bring up this topic at another meeting?
+EinMByte | Sure.
meeting-bot | [anonimal] If roadmap is too much, at least improve our readme. 
+EinMByte | I agree that we should first see if we can actually do what we want to do, so for example: can we change all of the necessary settings
```

Ticketing so we don't forget.

**Comment by bigreddmachine** [comment]
@anonimal - I realize you closed this issue but just wanted to let you know I've started looking into what we'd talked about, and I think it would be smart for me to talk with you more about needs. It's definitely doable to intercept `*.b32.i2p` and `*.i2p` using WebExtensions, and redirecting is also possible. But I need to better understand the "whats" on where we'd route to, etc, in order to figure of the "ifs" and "hows". I'll look for you on IRC over the next few days, though I must let you know I'll be traveling some so my availability might be limited until next week.

**Comment by anonimal** [comment]
Hi @bigreddmachine, I've opened #4 so we can continue there.  I (or maybe @EinMByte too) can fill you in on the details within the next day or so. Good to hear from you, talk to you soon.
